branch: release
verifyConditions:
  - '@semantic-release/github'

prepare:
  - path: '@semantic-release/exec'
    cmd: "JADX_VERSION=${nextRelease.version} ./gradlew clean dist"

preset: "angular"

generateNotes:
  - path: '@semantic-release/release-notes-generator'
    writerOpts:
      groupBy: "type"
      commitGroupsSort:
        - "feat"
        - "perf"
        - "fix"
      commitsSort: "header"

publish:
  - path: '@semantic-release/exec'
    cmd: "JADX_VERSION=${nextRelease.version} BINTRAY_PACKAGE=releases bash scripts/bintray-upload.sh"
  - path: '@semantic-release/github'
    assets:
      - path: 'build/*.zip'
      - path: 'build/*.exe'

success:
  - path: '@semantic-release/github'
    successComment: false

fail:
  - path: '@semantic-release/github'
    failComment: false
